/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const AchievementEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const AnxietyRating = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'worryScore' : IDL.Nat,
  'createdAt' : Timestamp,
  'confidenceScore' : IDL.Nat,
});
export const CelebrationEvent = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
});
export const InternshipEntry = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'company' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'startDate' : IDL.Text,
});
export const LeadershipRole = IDL.Record({
  'id' : IDL.Nat,
  'impact' : IDL.Text,
  'endDate' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'role' : IDL.Text,
  'organization' : IDL.Text,
  'startDate' : IDL.Text,
});
export const MoodCheckIn = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'mood' : IDL.Nat,
  'note' : IDL.Text,
  'createdAt' : Timestamp,
  'moodEmoji' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'applied' : IDL.Null,
  'waitlisted' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'deferred' : IDL.Null,
});
export const ApplicationEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'collegeName' : IDL.Text,
  'createdAt' : Timestamp,
  'deadline' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
});
export const EssayDraft = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'wordCount' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'version' : IDL.Nat,
  'timestamp' : Timestamp,
  'draftId' : IDL.Nat,
});
export const StressCheckIn = IDL.Record({
  'id' : IDL.Nat,
  'stressLevel' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'confidenceLevel' : IDL.Nat,
  'sleepHours' : IDL.Float64,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const TaskItem = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Text),
  'taskId' : IDL.Nat,
  'category' : IDL.Opt(IDL.Text),
  'priority' : TaskPriority,
});
export const TestScore = IDL.Record({
  'id' : IDL.Nat,
  'targetScore' : IDL.Opt(IDL.Nat),
  'date' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'testName' : IDL.Text,
  'sectionScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
});
export const ScholarshipTrackedStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'submitted' : IDL.Null,
  'awarded' : IDL.Null,
  'rejected' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const ScholarshipTracked = IDL.Record({
  'status' : ScholarshipTrackedStatus,
  'essayRequired' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'deadline' : IDL.Opt(IDL.Text),
  'appliedDate' : IDL.Opt(IDL.Text),
  'notes' : IDL.Opt(IDL.Text),
  'scholarshipId' : IDL.Nat,
});
export const SummerProgramStatus = IDL.Variant({
  'applied' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'interested' : IDL.Null,
});
export const SummerProgram = IDL.Record({
  'id' : IDL.Nat,
  'status' : SummerProgramStatus,
  'provider' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const VolunteerEntry = IDL.Record({
  'id' : IDL.Nat,
  'hours' : IDL.Float64,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'activity' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AmortizationEntry = IDL.Record({
  'month' : IDL.Nat,
  'principal' : IDL.Float64,
  'balance' : IDL.Float64,
  'interest' : IDL.Float64,
});
export const LoanCalculationResult = IDL.Record({
  'totalInterest' : IDL.Float64,
  'amortizationBreakdown' : IDL.Vec(AmortizationEntry),
  'totalPayment' : IDL.Float64,
  'monthlyPayment' : IDL.Float64,
});
export const Award = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const GpaType = IDL.Variant({
  'unweighted' : IDL.Null,
  'weighted' : IDL.Null,
});
export const FinancialAidPreference = IDL.Variant({
  'full' : IDL.Null,
  'half' : IDL.Null,
  'none' : IDL.Null,
});
export const StudentProfile = IDL.Record({
  'gpa' : IDL.Opt(IDL.Float64),
  'extracurriculars' : IDL.Vec(IDL.Text),
  'intendedMajor' : IDL.Text,
  'numberOfCourses' : IDL.Nat,
  'studyCountry' : IDL.Text,
  'actScore' : IDL.Opt(IDL.Nat),
  'workExperience' : IDL.Vec(IDL.Text),
  'awards' : IDL.Vec(Award),
  'gpaType' : GpaType,
  'financialAidPreference' : FinancialAidPreference,
  'satScore' : IDL.Opt(IDL.Nat),
  'dreamCollege' : IDL.Text,
  'weightedGpa' : IDL.Opt(IDL.Float64),
});
export const AiSuggestion = IDL.Record({
  'talkingPoints' : IDL.Vec(IDL.Text),
  'targetScoreSuggestions' : IDL.Vec(IDL.Text),
  'actionableAdvice' : IDL.Vec(IDL.Text),
  'brainstormingIdeas' : IDL.Vec(IDL.Text),
});
export const AlumniMessage = IDL.Record({
  'messageId' : IDL.Nat,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'collegeId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const AiMatchScore = IDL.Record({
  'reasoning' : IDL.Text,
  'score' : IDL.Float64,
  'collegeId' : IDL.Nat,
});
export const CollegeId = IDL.Nat;
export const FinancialAidTier = IDL.Variant({
  'fullRide' : IDL.Null,
  'noAid' : IDL.Null,
  'needBased' : IDL.Null,
  'meritOnly' : IDL.Null,
});
export const College = IDL.Record({
  'id' : CollegeId,
  'country' : IDL.Text,
  'acceptanceRate' : IDL.Float64,
  'name' : IDL.Text,
  'housingInfo' : IDL.Text,
  'tuition' : IDL.Nat,
  'website' : IDL.Text,
  'redditUrl' : IDL.Opt(IDL.Text),
  'majorsOffered' : IDL.Vec(IDL.Text),
  'discordUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
  'financialAidTier' : FinancialAidTier,
});
export const CourseRecommendation = IDL.Record({
  'provider' : IDL.Text,
  'description' : IDL.Text,
  'level' : IDL.Text,
  'subTopic' : IDL.Text,
  'courseName' : IDL.Text,
  'fieldOfStudy' : IDL.Text,
});
export const ExtracurricularRecommendation = IDL.Record({
  'impact' : IDL.Text,
  'activity' : IDL.Text,
  'reason' : IDL.Text,
});
export const InterviewQuestion = IDL.Record({
  'question' : IDL.Text,
  'category' : IDL.Text,
});
export const DeadlineStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
  'missed' : IDL.Null,
});
export const CollegeDeadline = IDL.Record({
  'status' : DeadlineStatus,
  'collegeName' : IDL.Text,
  'deadlineType' : IDL.Text,
  'dueDate' : IDL.Int,
  'collegeId' : IDL.Nat,
  'notes' : IDL.Text,
});
export const DocumentStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'verified' : IDL.Null,
  'submitted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const DocumentChecklistItem = IDL.Record({
  'id' : IDL.Nat,
  'status' : DocumentStatus,
  'name' : IDL.Text,
  'dueDate' : IDL.Opt(IDL.Int),
  'notes' : IDL.Text,
});
export const AdmissionOfficer = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'collegeId' : IDL.Nat,
  'registeredAt' : IDL.Int,
});
export const ScholarshipId = IDL.Nat;
export const OfficerContentType = IDL.Variant({
  'tip' : IDL.Null,
  'video' : IDL.Null,
  'announcement' : IDL.Null,
  'insight' : IDL.Null,
});
export const OfficerContent = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'officerId' : IDL.Principal,
  'contentType' : OfficerContentType,
  'body' : IDL.Text,
  'collegeId' : IDL.Nat,
  'timestamp' : IDL.Int,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const UserId = IDL.Principal;
export const OfficerVerificationStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const OfficerProfile = IDL.Record({
  'title' : IDL.Text,
  'userId' : UserId,
  'institution' : IDL.Text,
  'submittedAt' : Timestamp,
  'reviewedAt' : IDL.Opt(Timestamp),
  'govIdFilename' : IDL.Text,
  'verificationStatus' : OfficerVerificationStatus,
});
export const PortfolioChecklistItem = IDL.Record({
  'completed' : IDL.Bool,
  'itemLabel' : IDL.Text,
  'updatedAt' : Timestamp,
  'itemKey' : IDL.Text,
});
export const SalaryBookmark = IDL.Record({
  'id' : IDL.Nat,
  'major' : IDL.Text,
  'medianSalary' : IDL.Opt(IDL.Nat),
  'notes' : IDL.Text,
  'savedAt' : Timestamp,
  'collegeOrRegion' : IDL.Text,
});
export const SavedCareerPath = IDL.Record({
  'id' : IDL.Nat,
  'major' : IDL.Text,
  'description' : IDL.Text,
  'savedAt' : Timestamp,
  'careerTitle' : IDL.Text,
});
export const Scholarship = IDL.Record({
  'id' : ScholarshipId,
  'requiresFinancialNeed' : IDL.Bool,
  'applyLink' : IDL.Text,
  'name' : IDL.Text,
  'deadline' : IDL.Text,
  'eligibilityMinGpa' : IDL.Opt(IDL.Float64),
  'eligibilityMajor' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'eligibilityMaxGpa' : IDL.Opt(IDL.Float64),
});
export const OfficerContentInput = IDL.Record({
  'title' : IDL.Text,
  'contentType' : OfficerContentType,
  'body' : IDL.Text,
  'collegeId' : IDL.Nat,
  'videoUrl' : IDL.Opt(IDL.Text),
});
export const ScholarshipFilter = IDL.Record({
  'major' : IDL.Opt(IDL.Text),
  'requiresFinancialNeed' : IDL.Opt(IDL.Bool),
  'minGpa' : IDL.Opt(IDL.Float64),
});
export const EssayReview = IDL.Record({
  'overallScore' : IDL.Nat,
  'strengths' : IDL.Vec(IDL.Text),
  'improvements' : IDL.Vec(IDL.Text),
  'feedback' : IDL.Text,
  'grade' : IDL.Text,
});
export const InterviewFeedback = IDL.Record({
  'question' : IDL.Text,
  'feedback' : IDL.Text,
  'answer' : IDL.Text,
  'score' : IDL.Nat,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addAchievement' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [AchievementEntry],
      [],
    ),
  'addAnxietyRating' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [AnxietyRating],
      [],
    ),
  'addCelebrationEvent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [CelebrationEvent],
      [],
    ),
  'addInternship' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
      [InternshipEntry],
      [],
    ),
  'addLeadershipRole' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
      [LeadershipRole],
      [],
    ),
  'addMoodCheckIn' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [MoodCheckIn],
      [],
    ),
  'addMyApplication' : IDL.Func(
      [IDL.Text, ApplicationStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ApplicationEntry],
      [],
    ),
  'addMyEssayDraft' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [EssayDraft],
      [],
    ),
  'addMyStressCheckIn' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat],
      [StressCheckIn],
      [],
    ),
  'addMyTask' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), TaskPriority, IDL.Opt(IDL.Text)],
      [TaskItem],
      [],
    ),
  'addMyTestScore' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [TestScore],
      [],
    ),
  'addMyTrackedScholarship' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Bool, IDL.Opt(IDL.Text)],
      [ScholarshipTracked],
      [],
    ),
  'addSummerProgram' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, SummerProgramStatus],
      [SummerProgram],
      [],
    ),
  'addVolunteerEntry' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text],
      [VolunteerEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateLoan' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
      [LoanCalculationResult],
      ['query'],
    ),
  'deleteAchievement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteInternship' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteLeadershipRole' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMyApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMyEssayDraft' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMyTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMyTestScore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMyTrackedScholarship' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSummerProgram' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteVolunteerEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(AchievementEntry)], ['query']),
  'getAiSuggestions' : IDL.Func([StudentProfile], [AiSuggestion], []),
  'getAlumniMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AlumniMessage)],
      ['query'],
    ),
  'getAnxietyRatings' : IDL.Func([], [IDL.Vec(AnxietyRating)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCelebrationEvents' : IDL.Func([], [IDL.Vec(CelebrationEvent)], ['query']),
  'getCollegeMatchScore' : IDL.Func(
      [IDL.Nat, IDL.Text, StudentProfile],
      [AiMatchScore],
      [],
    ),
  'getColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
  'getCollegesByCountry' : IDL.Func([IDL.Text], [IDL.Vec(College)], ['query']),
  'getCollegesByFinancialAid' : IDL.Func(
      [FinancialAidTier],
      [IDL.Vec(College)],
      ['query'],
    ),
  'getCourseRecommendations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CourseRecommendation)],
      [],
    ),
  'getExtracurricularRecommendations' : IDL.Func(
      [StudentProfile],
      [IDL.Vec(ExtracurricularRecommendation)],
      [],
    ),
  'getGeminiApiKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getInternships' : IDL.Func([], [IDL.Vec(InternshipEntry)], ['query']),
  'getInterviewQuestions' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(InterviewQuestion)],
      [],
    ),
  'getLeadershipRoles' : IDL.Func([], [IDL.Vec(LeadershipRole)], ['query']),
  'getMoodCheckIns' : IDL.Func([], [IDL.Vec(MoodCheckIn)], ['query']),
  'getMyDeadlines' : IDL.Func([], [IDL.Vec(CollegeDeadline)], ['query']),
  'getMyDocumentChecklist' : IDL.Func(
      [],
      [IDL.Vec(DocumentChecklistItem)],
      ['query'],
    ),
  'getMyOfficerProfile' : IDL.Func([], [IDL.Opt(AdmissionOfficer)], ['query']),
  'getMyScholarshipShortlist' : IDL.Func(
      [],
      [IDL.Vec(ScholarshipId)],
      ['query'],
    ),
  'getOfficerContent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(OfficerContent)],
      ['query'],
    ),
  'getOfficerProfile' : IDL.Func([], [IDL.Opt(OfficerProfile)], ['query']),
  'getPortfolioChecklist' : IDL.Func(
      [],
      [IDL.Vec(PortfolioChecklistItem)],
      ['query'],
    ),
  'getSalaryBookmarks' : IDL.Func([], [IDL.Vec(SalaryBookmark)], ['query']),
  'getSavedCareerPaths' : IDL.Func([], [IDL.Vec(SavedCareerPath)], ['query']),
  'getScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
  'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getSummerPrograms' : IDL.Func([], [IDL.Vec(SummerProgram)], ['query']),
  'getVolunteerEntries' : IDL.Func([], [IDL.Vec(VolunteerEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyApplications' : IDL.Func([], [IDL.Vec(ApplicationEntry)], ['query']),
  'listMyEssayDrafts' : IDL.Func([], [IDL.Vec(EssayDraft)], ['query']),
  'listMyStressCheckIns' : IDL.Func([], [IDL.Vec(StressCheckIn)], ['query']),
  'listMyTasks' : IDL.Func([], [IDL.Vec(TaskItem)], ['query']),
  'listMyTestScores' : IDL.Func([], [IDL.Vec(TestScore)], ['query']),
  'listMyTrackedScholarships' : IDL.Func(
      [],
      [IDL.Vec(ScholarshipTracked)],
      ['query'],
    ),
  'listPendingOfficers' : IDL.Func([], [IDL.Vec(OfficerProfile)], ['query']),
  'postAlumniMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'postOfficerContent' : IDL.Func([OfficerContentInput], [IDL.Nat], []),
  'queryScholarships' : IDL.Func(
      [ScholarshipFilter],
      [IDL.Vec(Scholarship)],
      ['query'],
    ),
  'registerOfficer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeSalaryBookmark' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeSavedCareerPath' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'reviewEssay' : IDL.Func([IDL.Text, IDL.Text], [EssayReview], []),
  'saveCareerPath' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SavedCareerPath],
      [],
    ),
  'saveMyDeadlines' : IDL.Func([IDL.Vec(CollegeDeadline)], [], []),
  'saveMyDocumentChecklist' : IDL.Func(
      [IDL.Vec(DocumentChecklistItem)],
      [],
      [],
    ),
  'saveMyScholarshipShortlist' : IDL.Func([IDL.Vec(ScholarshipId)], [], []),
  'saveSalaryBookmark' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
      [SalaryBookmark],
      [],
    ),
  'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
  'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
  'submitInterviewAnswer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [InterviewFeedback],
      [],
    ),
  'submitOfficerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [OfficerProfile],
      [],
    ),
  'toggleMyTask' : IDL.Func([IDL.Nat], [IDL.Opt(TaskItem)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMyApplication' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(ApplicationStatus),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Opt(ApplicationEntry)],
      [],
    ),
  'updateMyEssayDraft' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [IDL.Opt(EssayDraft)],
      [],
    ),
  'updateMyTestScore' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Opt(TestScore)],
      [],
    ),
  'updateMyTrackedScholarship' : IDL.Func(
      [
        IDL.Nat,
        IDL.Opt(ScholarshipTrackedStatus),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Opt(ScholarshipTracked)],
      [],
    ),
  'updateOfficerVerificationStatus' : IDL.Func(
      [UserId, OfficerVerificationStatus],
      [IDL.Bool],
      [],
    ),
  'upsertPortfolioChecklist' : IDL.Func(
      [IDL.Vec(PortfolioChecklistItem)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const AchievementEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const AnxietyRating = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'worryScore' : IDL.Nat,
    'createdAt' : Timestamp,
    'confidenceScore' : IDL.Nat,
  });
  const CelebrationEvent = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
  });
  const InternshipEntry = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'company' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'startDate' : IDL.Text,
  });
  const LeadershipRole = IDL.Record({
    'id' : IDL.Nat,
    'impact' : IDL.Text,
    'endDate' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'role' : IDL.Text,
    'organization' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const MoodCheckIn = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'mood' : IDL.Nat,
    'note' : IDL.Text,
    'createdAt' : Timestamp,
    'moodEmoji' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'applied' : IDL.Null,
    'waitlisted' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'deferred' : IDL.Null,
  });
  const ApplicationEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'collegeName' : IDL.Text,
    'createdAt' : Timestamp,
    'deadline' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
  });
  const EssayDraft = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'wordCount' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'version' : IDL.Nat,
    'timestamp' : Timestamp,
    'draftId' : IDL.Nat,
  });
  const StressCheckIn = IDL.Record({
    'id' : IDL.Nat,
    'stressLevel' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'confidenceLevel' : IDL.Nat,
    'sleepHours' : IDL.Float64,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const TaskItem = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Text),
    'taskId' : IDL.Nat,
    'category' : IDL.Opt(IDL.Text),
    'priority' : TaskPriority,
  });
  const TestScore = IDL.Record({
    'id' : IDL.Nat,
    'targetScore' : IDL.Opt(IDL.Nat),
    'date' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'testName' : IDL.Text,
    'sectionScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  });
  const ScholarshipTrackedStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'submitted' : IDL.Null,
    'awarded' : IDL.Null,
    'rejected' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const ScholarshipTracked = IDL.Record({
    'status' : ScholarshipTrackedStatus,
    'essayRequired' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'deadline' : IDL.Opt(IDL.Text),
    'appliedDate' : IDL.Opt(IDL.Text),
    'notes' : IDL.Opt(IDL.Text),
    'scholarshipId' : IDL.Nat,
  });
  const SummerProgramStatus = IDL.Variant({
    'applied' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'interested' : IDL.Null,
  });
  const SummerProgram = IDL.Record({
    'id' : IDL.Nat,
    'status' : SummerProgramStatus,
    'provider' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const VolunteerEntry = IDL.Record({
    'id' : IDL.Nat,
    'hours' : IDL.Float64,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'activity' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AmortizationEntry = IDL.Record({
    'month' : IDL.Nat,
    'principal' : IDL.Float64,
    'balance' : IDL.Float64,
    'interest' : IDL.Float64,
  });
  const LoanCalculationResult = IDL.Record({
    'totalInterest' : IDL.Float64,
    'amortizationBreakdown' : IDL.Vec(AmortizationEntry),
    'totalPayment' : IDL.Float64,
    'monthlyPayment' : IDL.Float64,
  });
  const Award = IDL.Record({ 'title' : IDL.Text, 'description' : IDL.Text });
  const GpaType = IDL.Variant({
    'unweighted' : IDL.Null,
    'weighted' : IDL.Null,
  });
  const FinancialAidPreference = IDL.Variant({
    'full' : IDL.Null,
    'half' : IDL.Null,
    'none' : IDL.Null,
  });
  const StudentProfile = IDL.Record({
    'gpa' : IDL.Opt(IDL.Float64),
    'extracurriculars' : IDL.Vec(IDL.Text),
    'intendedMajor' : IDL.Text,
    'numberOfCourses' : IDL.Nat,
    'studyCountry' : IDL.Text,
    'actScore' : IDL.Opt(IDL.Nat),
    'workExperience' : IDL.Vec(IDL.Text),
    'awards' : IDL.Vec(Award),
    'gpaType' : GpaType,
    'financialAidPreference' : FinancialAidPreference,
    'satScore' : IDL.Opt(IDL.Nat),
    'dreamCollege' : IDL.Text,
    'weightedGpa' : IDL.Opt(IDL.Float64),
  });
  const AiSuggestion = IDL.Record({
    'talkingPoints' : IDL.Vec(IDL.Text),
    'targetScoreSuggestions' : IDL.Vec(IDL.Text),
    'actionableAdvice' : IDL.Vec(IDL.Text),
    'brainstormingIdeas' : IDL.Vec(IDL.Text),
  });
  const AlumniMessage = IDL.Record({
    'messageId' : IDL.Nat,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'collegeId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const AiMatchScore = IDL.Record({
    'reasoning' : IDL.Text,
    'score' : IDL.Float64,
    'collegeId' : IDL.Nat,
  });
  const CollegeId = IDL.Nat;
  const FinancialAidTier = IDL.Variant({
    'fullRide' : IDL.Null,
    'noAid' : IDL.Null,
    'needBased' : IDL.Null,
    'meritOnly' : IDL.Null,
  });
  const College = IDL.Record({
    'id' : CollegeId,
    'country' : IDL.Text,
    'acceptanceRate' : IDL.Float64,
    'name' : IDL.Text,
    'housingInfo' : IDL.Text,
    'tuition' : IDL.Nat,
    'website' : IDL.Text,
    'redditUrl' : IDL.Opt(IDL.Text),
    'majorsOffered' : IDL.Vec(IDL.Text),
    'discordUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
    'financialAidTier' : FinancialAidTier,
  });
  const CourseRecommendation = IDL.Record({
    'provider' : IDL.Text,
    'description' : IDL.Text,
    'level' : IDL.Text,
    'subTopic' : IDL.Text,
    'courseName' : IDL.Text,
    'fieldOfStudy' : IDL.Text,
  });
  const ExtracurricularRecommendation = IDL.Record({
    'impact' : IDL.Text,
    'activity' : IDL.Text,
    'reason' : IDL.Text,
  });
  const InterviewQuestion = IDL.Record({
    'question' : IDL.Text,
    'category' : IDL.Text,
  });
  const DeadlineStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
    'missed' : IDL.Null,
  });
  const CollegeDeadline = IDL.Record({
    'status' : DeadlineStatus,
    'collegeName' : IDL.Text,
    'deadlineType' : IDL.Text,
    'dueDate' : IDL.Int,
    'collegeId' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const DocumentStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'verified' : IDL.Null,
    'submitted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const DocumentChecklistItem = IDL.Record({
    'id' : IDL.Nat,
    'status' : DocumentStatus,
    'name' : IDL.Text,
    'dueDate' : IDL.Opt(IDL.Int),
    'notes' : IDL.Text,
  });
  const AdmissionOfficer = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'collegeId' : IDL.Nat,
    'registeredAt' : IDL.Int,
  });
  const ScholarshipId = IDL.Nat;
  const OfficerContentType = IDL.Variant({
    'tip' : IDL.Null,
    'video' : IDL.Null,
    'announcement' : IDL.Null,
    'insight' : IDL.Null,
  });
  const OfficerContent = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'officerId' : IDL.Principal,
    'contentType' : OfficerContentType,
    'body' : IDL.Text,
    'collegeId' : IDL.Nat,
    'timestamp' : IDL.Int,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const UserId = IDL.Principal;
  const OfficerVerificationStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const OfficerProfile = IDL.Record({
    'title' : IDL.Text,
    'userId' : UserId,
    'institution' : IDL.Text,
    'submittedAt' : Timestamp,
    'reviewedAt' : IDL.Opt(Timestamp),
    'govIdFilename' : IDL.Text,
    'verificationStatus' : OfficerVerificationStatus,
  });
  const PortfolioChecklistItem = IDL.Record({
    'completed' : IDL.Bool,
    'itemLabel' : IDL.Text,
    'updatedAt' : Timestamp,
    'itemKey' : IDL.Text,
  });
  const SalaryBookmark = IDL.Record({
    'id' : IDL.Nat,
    'major' : IDL.Text,
    'medianSalary' : IDL.Opt(IDL.Nat),
    'notes' : IDL.Text,
    'savedAt' : Timestamp,
    'collegeOrRegion' : IDL.Text,
  });
  const SavedCareerPath = IDL.Record({
    'id' : IDL.Nat,
    'major' : IDL.Text,
    'description' : IDL.Text,
    'savedAt' : Timestamp,
    'careerTitle' : IDL.Text,
  });
  const Scholarship = IDL.Record({
    'id' : ScholarshipId,
    'requiresFinancialNeed' : IDL.Bool,
    'applyLink' : IDL.Text,
    'name' : IDL.Text,
    'deadline' : IDL.Text,
    'eligibilityMinGpa' : IDL.Opt(IDL.Float64),
    'eligibilityMajor' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'eligibilityMaxGpa' : IDL.Opt(IDL.Float64),
  });
  const OfficerContentInput = IDL.Record({
    'title' : IDL.Text,
    'contentType' : OfficerContentType,
    'body' : IDL.Text,
    'collegeId' : IDL.Nat,
    'videoUrl' : IDL.Opt(IDL.Text),
  });
  const ScholarshipFilter = IDL.Record({
    'major' : IDL.Opt(IDL.Text),
    'requiresFinancialNeed' : IDL.Opt(IDL.Bool),
    'minGpa' : IDL.Opt(IDL.Float64),
  });
  const EssayReview = IDL.Record({
    'overallScore' : IDL.Nat,
    'strengths' : IDL.Vec(IDL.Text),
    'improvements' : IDL.Vec(IDL.Text),
    'feedback' : IDL.Text,
    'grade' : IDL.Text,
  });
  const InterviewFeedback = IDL.Record({
    'question' : IDL.Text,
    'feedback' : IDL.Text,
    'answer' : IDL.Text,
    'score' : IDL.Nat,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addAchievement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [AchievementEntry],
        [],
      ),
    'addAnxietyRating' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [AnxietyRating],
        [],
      ),
    'addCelebrationEvent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [CelebrationEvent],
        [],
      ),
    'addInternship' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(IDL.Text)],
        [InternshipEntry],
        [],
      ),
    'addLeadershipRole' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Text],
        [LeadershipRole],
        [],
      ),
    'addMoodCheckIn' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [MoodCheckIn],
        [],
      ),
    'addMyApplication' : IDL.Func(
        [IDL.Text, ApplicationStatus, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ApplicationEntry],
        [],
      ),
    'addMyEssayDraft' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [EssayDraft],
        [],
      ),
    'addMyStressCheckIn' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Nat],
        [StressCheckIn],
        [],
      ),
    'addMyTask' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), TaskPriority, IDL.Opt(IDL.Text)],
        [TaskItem],
        [],
      ),
    'addMyTestScore' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [TestScore],
        [],
      ),
    'addMyTrackedScholarship' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Bool, IDL.Opt(IDL.Text)],
        [ScholarshipTracked],
        [],
      ),
    'addSummerProgram' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, SummerProgramStatus],
        [SummerProgram],
        [],
      ),
    'addVolunteerEntry' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text],
        [VolunteerEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateLoan' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Nat],
        [LoanCalculationResult],
        ['query'],
      ),
    'deleteAchievement' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteInternship' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteLeadershipRole' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMyApplication' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMyEssayDraft' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMyTask' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMyTestScore' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMyTrackedScholarship' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSummerProgram' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteVolunteerEntry' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(AchievementEntry)], ['query']),
    'getAiSuggestions' : IDL.Func([StudentProfile], [AiSuggestion], []),
    'getAlumniMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AlumniMessage)],
        ['query'],
      ),
    'getAnxietyRatings' : IDL.Func([], [IDL.Vec(AnxietyRating)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCelebrationEvents' : IDL.Func(
        [],
        [IDL.Vec(CelebrationEvent)],
        ['query'],
      ),
    'getCollegeMatchScore' : IDL.Func(
        [IDL.Nat, IDL.Text, StudentProfile],
        [AiMatchScore],
        [],
      ),
    'getColleges' : IDL.Func([], [IDL.Vec(College)], ['query']),
    'getCollegesByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(College)],
        ['query'],
      ),
    'getCollegesByFinancialAid' : IDL.Func(
        [FinancialAidTier],
        [IDL.Vec(College)],
        ['query'],
      ),
    'getCourseRecommendations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CourseRecommendation)],
        [],
      ),
    'getExtracurricularRecommendations' : IDL.Func(
        [StudentProfile],
        [IDL.Vec(ExtracurricularRecommendation)],
        [],
      ),
    'getGeminiApiKeyStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getInternships' : IDL.Func([], [IDL.Vec(InternshipEntry)], ['query']),
    'getInterviewQuestions' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(InterviewQuestion)],
        [],
      ),
    'getLeadershipRoles' : IDL.Func([], [IDL.Vec(LeadershipRole)], ['query']),
    'getMoodCheckIns' : IDL.Func([], [IDL.Vec(MoodCheckIn)], ['query']),
    'getMyDeadlines' : IDL.Func([], [IDL.Vec(CollegeDeadline)], ['query']),
    'getMyDocumentChecklist' : IDL.Func(
        [],
        [IDL.Vec(DocumentChecklistItem)],
        ['query'],
      ),
    'getMyOfficerProfile' : IDL.Func(
        [],
        [IDL.Opt(AdmissionOfficer)],
        ['query'],
      ),
    'getMyScholarshipShortlist' : IDL.Func(
        [],
        [IDL.Vec(ScholarshipId)],
        ['query'],
      ),
    'getOfficerContent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(OfficerContent)],
        ['query'],
      ),
    'getOfficerProfile' : IDL.Func([], [IDL.Opt(OfficerProfile)], ['query']),
    'getPortfolioChecklist' : IDL.Func(
        [],
        [IDL.Vec(PortfolioChecklistItem)],
        ['query'],
      ),
    'getSalaryBookmarks' : IDL.Func([], [IDL.Vec(SalaryBookmark)], ['query']),
    'getSavedCareerPaths' : IDL.Func([], [IDL.Vec(SavedCareerPath)], ['query']),
    'getScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], ['query']),
    'getStudentProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getSummerPrograms' : IDL.Func([], [IDL.Vec(SummerProgram)], ['query']),
    'getVolunteerEntries' : IDL.Func([], [IDL.Vec(VolunteerEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyApplications' : IDL.Func([], [IDL.Vec(ApplicationEntry)], ['query']),
    'listMyEssayDrafts' : IDL.Func([], [IDL.Vec(EssayDraft)], ['query']),
    'listMyStressCheckIns' : IDL.Func([], [IDL.Vec(StressCheckIn)], ['query']),
    'listMyTasks' : IDL.Func([], [IDL.Vec(TaskItem)], ['query']),
    'listMyTestScores' : IDL.Func([], [IDL.Vec(TestScore)], ['query']),
    'listMyTrackedScholarships' : IDL.Func(
        [],
        [IDL.Vec(ScholarshipTracked)],
        ['query'],
      ),
    'listPendingOfficers' : IDL.Func([], [IDL.Vec(OfficerProfile)], ['query']),
    'postAlumniMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'postOfficerContent' : IDL.Func([OfficerContentInput], [IDL.Nat], []),
    'queryScholarships' : IDL.Func(
        [ScholarshipFilter],
        [IDL.Vec(Scholarship)],
        ['query'],
      ),
    'registerOfficer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeSalaryBookmark' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeSavedCareerPath' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'reviewEssay' : IDL.Func([IDL.Text, IDL.Text], [EssayReview], []),
    'saveCareerPath' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SavedCareerPath],
        [],
      ),
    'saveMyDeadlines' : IDL.Func([IDL.Vec(CollegeDeadline)], [], []),
    'saveMyDocumentChecklist' : IDL.Func(
        [IDL.Vec(DocumentChecklistItem)],
        [],
        [],
      ),
    'saveMyScholarshipShortlist' : IDL.Func([IDL.Vec(ScholarshipId)], [], []),
    'saveSalaryBookmark' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Text],
        [SalaryBookmark],
        [],
      ),
    'saveStudentProfile' : IDL.Func([StudentProfile], [], []),
    'setGeminiApiKey' : IDL.Func([IDL.Text], [], []),
    'submitInterviewAnswer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [InterviewFeedback],
        [],
      ),
    'submitOfficerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [OfficerProfile],
        [],
      ),
    'toggleMyTask' : IDL.Func([IDL.Nat], [IDL.Opt(TaskItem)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMyApplication' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(ApplicationStatus),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Opt(ApplicationEntry)],
        [],
      ),
    'updateMyEssayDraft' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [IDL.Opt(EssayDraft)],
        [],
      ),
    'updateMyTestScore' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Opt(TestScore)],
        [],
      ),
    'updateMyTrackedScholarship' : IDL.Func(
        [
          IDL.Nat,
          IDL.Opt(ScholarshipTrackedStatus),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Opt(ScholarshipTracked)],
        [],
      ),
    'updateOfficerVerificationStatus' : IDL.Func(
        [UserId, OfficerVerificationStatus],
        [IDL.Bool],
        [],
      ),
    'upsertPortfolioChecklist' : IDL.Func(
        [IDL.Vec(PortfolioChecklistItem)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };