/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AchievementEntry {
  'id' : bigint,
  'date' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface AdmissionOfficer {
  'principal' : Principal,
  'name' : string,
  'collegeId' : bigint,
  'registeredAt' : bigint,
}
export interface AiMatchScore {
  'reasoning' : string,
  'score' : number,
  'collegeId' : bigint,
}
export interface AiSuggestion {
  'talkingPoints' : Array<string>,
  'targetScoreSuggestions' : Array<string>,
  'actionableAdvice' : Array<string>,
  'brainstormingIdeas' : Array<string>,
}
export interface AlumniMessage {
  'messageId' : bigint,
  'authorName' : string,
  'author' : Principal,
  'collegeId' : bigint,
  'message' : string,
  'timestamp' : bigint,
}
export interface AmortizationEntry {
  'month' : bigint,
  'principal' : number,
  'balance' : number,
  'interest' : number,
}
export interface AnxietyRating {
  'id' : bigint,
  'date' : string,
  'worryScore' : bigint,
  'createdAt' : Timestamp,
  'confidenceScore' : bigint,
}
export interface ApplicationEntry {
  'id' : bigint,
  'status' : ApplicationStatus,
  'collegeName' : string,
  'createdAt' : Timestamp,
  'deadline' : [] | [string],
  'updatedAt' : Timestamp,
  'notes' : [] | [string],
}
export type ApplicationStatus = { 'applied' : null } |
  { 'waitlisted' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'deferred' : null };
export interface Award { 'title' : string, 'description' : string }
export interface CelebrationEvent {
  'id' : bigint,
  'date' : string,
  'createdAt' : Timestamp,
  'description' : string,
}
export interface College {
  'id' : CollegeId,
  'country' : string,
  'acceptanceRate' : number,
  'name' : string,
  'housingInfo' : string,
  'tuition' : bigint,
  'website' : string,
  'redditUrl' : [] | [string],
  'majorsOffered' : Array<string>,
  'discordUrl' : [] | [string],
  'location' : string,
  'financialAidTier' : FinancialAidTier,
}
export interface CollegeDeadline {
  'status' : DeadlineStatus,
  'collegeName' : string,
  'deadlineType' : string,
  'dueDate' : bigint,
  'collegeId' : bigint,
  'notes' : string,
}
export type CollegeId = bigint;
export interface CourseRecommendation {
  'provider' : string,
  'description' : string,
  'level' : string,
  'subTopic' : string,
  'courseName' : string,
  'fieldOfStudy' : string,
}
export type DeadlineStatus = { 'upcoming' : null } |
  { 'completed' : null } |
  { 'missed' : null };
export interface DocumentChecklistItem {
  'id' : bigint,
  'status' : DocumentStatus,
  'name' : string,
  'dueDate' : [] | [bigint],
  'notes' : string,
}
export type DocumentStatus = { 'notStarted' : null } |
  { 'verified' : null } |
  { 'submitted' : null } |
  { 'inProgress' : null };
export interface EssayDraft {
  'title' : string,
  'content' : string,
  'wordCount' : bigint,
  'tags' : Array<string>,
  'version' : bigint,
  'timestamp' : Timestamp,
  'draftId' : bigint,
}
export interface EssayReview {
  'overallScore' : bigint,
  'strengths' : Array<string>,
  'improvements' : Array<string>,
  'feedback' : string,
  'grade' : string,
}
export interface ExtracurricularRecommendation {
  'impact' : string,
  'activity' : string,
  'reason' : string,
}
export type FinancialAidPreference = { 'full' : null } |
  { 'half' : null } |
  { 'none' : null };
export type FinancialAidTier = { 'fullRide' : null } |
  { 'noAid' : null } |
  { 'needBased' : null } |
  { 'meritOnly' : null };
export type GpaType = { 'unweighted' : null } |
  { 'weighted' : null };
export interface InternshipEntry {
  'id' : bigint,
  'endDate' : [] | [string],
  'createdAt' : Timestamp,
  'role' : string,
  'company' : string,
  'skills' : Array<string>,
  'startDate' : string,
}
export interface InterviewFeedback {
  'question' : string,
  'feedback' : string,
  'answer' : string,
  'score' : bigint,
}
export interface InterviewQuestion { 'question' : string, 'category' : string }
export interface LeadershipRole {
  'id' : bigint,
  'impact' : string,
  'endDate' : [] | [string],
  'createdAt' : Timestamp,
  'role' : string,
  'organization' : string,
  'startDate' : string,
}
export interface LoanCalculationResult {
  'totalInterest' : number,
  'amortizationBreakdown' : Array<AmortizationEntry>,
  'totalPayment' : number,
  'monthlyPayment' : number,
}
export interface MoodCheckIn {
  'id' : bigint,
  'date' : string,
  'mood' : bigint,
  'note' : string,
  'createdAt' : Timestamp,
  'moodEmoji' : string,
}
export interface OfficerContent {
  'id' : bigint,
  'title' : string,
  'officerId' : Principal,
  'contentType' : OfficerContentType,
  'body' : string,
  'collegeId' : bigint,
  'timestamp' : bigint,
  'videoUrl' : [] | [string],
}
export interface OfficerContentInput {
  'title' : string,
  'contentType' : OfficerContentType,
  'body' : string,
  'collegeId' : bigint,
  'videoUrl' : [] | [string],
}
export type OfficerContentType = { 'tip' : null } |
  { 'video' : null } |
  { 'announcement' : null } |
  { 'insight' : null };
export interface OfficerProfile {
  'title' : string,
  'userId' : UserId,
  'institution' : string,
  'submittedAt' : Timestamp,
  'reviewedAt' : [] | [Timestamp],
  'govIdFilename' : string,
  'verificationStatus' : OfficerVerificationStatus,
}
export type OfficerVerificationStatus = { 'verified' : null } |
  { 'pending' : null } |
  { 'rejected' : null };
export interface PortfolioChecklistItem {
  'completed' : boolean,
  'itemLabel' : string,
  'updatedAt' : Timestamp,
  'itemKey' : string,
}
export interface SalaryBookmark {
  'id' : bigint,
  'major' : string,
  'medianSalary' : [] | [bigint],
  'notes' : string,
  'savedAt' : Timestamp,
  'collegeOrRegion' : string,
}
export interface SavedCareerPath {
  'id' : bigint,
  'major' : string,
  'description' : string,
  'savedAt' : Timestamp,
  'careerTitle' : string,
}
export interface Scholarship {
  'id' : ScholarshipId,
  'requiresFinancialNeed' : boolean,
  'applyLink' : string,
  'name' : string,
  'deadline' : string,
  'eligibilityMinGpa' : [] | [number],
  'eligibilityMajor' : [] | [string],
  'amount' : bigint,
  'eligibilityMaxGpa' : [] | [number],
}
export interface ScholarshipFilter {
  'major' : [] | [string],
  'requiresFinancialNeed' : [] | [boolean],
  'minGpa' : [] | [number],
}
export type ScholarshipId = bigint;
export interface ScholarshipTracked {
  'status' : ScholarshipTrackedStatus,
  'essayRequired' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'deadline' : [] | [string],
  'appliedDate' : [] | [string],
  'notes' : [] | [string],
  'scholarshipId' : bigint,
}
export type ScholarshipTrackedStatus = { 'notStarted' : null } |
  { 'submitted' : null } |
  { 'awarded' : null } |
  { 'rejected' : null } |
  { 'inProgress' : null };
export interface StressCheckIn {
  'id' : bigint,
  'stressLevel' : bigint,
  'date' : string,
  'createdAt' : Timestamp,
  'confidenceLevel' : bigint,
  'sleepHours' : number,
}
export interface StudentProfile {
  'gpa' : [] | [number],
  'extracurriculars' : Array<string>,
  'intendedMajor' : string,
  'numberOfCourses' : bigint,
  'studyCountry' : string,
  'actScore' : [] | [bigint],
  'workExperience' : Array<string>,
  'awards' : Array<Award>,
  'gpaType' : GpaType,
  'financialAidPreference' : FinancialAidPreference,
  'satScore' : [] | [bigint],
  'dreamCollege' : string,
  'weightedGpa' : [] | [number],
}
export interface SummerProgram {
  'id' : bigint,
  'status' : SummerProgramStatus,
  'provider' : string,
  'date' : string,
  'name' : string,
  'createdAt' : Timestamp,
}
export type SummerProgramStatus = { 'applied' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'interested' : null };
export interface TaskItem {
  'title' : string,
  'createdAt' : Timestamp,
  'completed' : boolean,
  'dueDate' : [] | [string],
  'taskId' : bigint,
  'category' : [] | [string],
  'priority' : TaskPriority,
}
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface TestScore {
  'id' : bigint,
  'targetScore' : [] | [bigint],
  'date' : [] | [string],
  'createdAt' : Timestamp,
  'testName' : string,
  'sectionScores' : Array<[string, bigint]>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VolunteerEntry {
  'id' : bigint,
  'hours' : number,
  'date' : string,
  'createdAt' : Timestamp,
  'activity' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addAchievement' : ActorMethod<[string, string, string], AchievementEntry>,
  'addAnxietyRating' : ActorMethod<[string, bigint, bigint], AnxietyRating>,
  'addCelebrationEvent' : ActorMethod<[string, string], CelebrationEvent>,
  'addInternship' : ActorMethod<
    [string, string, string, [] | [string], Array<string>],
    InternshipEntry
  >,
  'addLeadershipRole' : ActorMethod<
    [string, string, string, [] | [string], string],
    LeadershipRole
  >,
  'addMoodCheckIn' : ActorMethod<[string, bigint, string, string], MoodCheckIn>,
  'addMyApplication' : ActorMethod<
    [string, ApplicationStatus, [] | [string], [] | [string]],
    ApplicationEntry
  >,
  'addMyEssayDraft' : ActorMethod<[string, string, Array<string>], EssayDraft>,
  'addMyStressCheckIn' : ActorMethod<
    [string, bigint, number, bigint],
    StressCheckIn
  >,
  'addMyTask' : ActorMethod<
    [string, [] | [string], TaskPriority, [] | [string]],
    TaskItem
  >,
  'addMyTestScore' : ActorMethod<
    [string, Array<[string, bigint]>, [] | [string], [] | [bigint]],
    TestScore
  >,
  'addMyTrackedScholarship' : ActorMethod<
    [string, [] | [string], boolean, [] | [string]],
    ScholarshipTracked
  >,
  'addSummerProgram' : ActorMethod<
    [string, string, string, SummerProgramStatus],
    SummerProgram
  >,
  'addVolunteerEntry' : ActorMethod<[string, number, string], VolunteerEntry>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateLoan' : ActorMethod<
    [number, number, number, bigint],
    LoanCalculationResult
  >,
  'deleteAchievement' : ActorMethod<[bigint], boolean>,
  'deleteInternship' : ActorMethod<[bigint], boolean>,
  'deleteLeadershipRole' : ActorMethod<[bigint], boolean>,
  'deleteMyApplication' : ActorMethod<[bigint], boolean>,
  'deleteMyEssayDraft' : ActorMethod<[bigint], boolean>,
  'deleteMyTask' : ActorMethod<[bigint], boolean>,
  'deleteMyTestScore' : ActorMethod<[bigint], boolean>,
  'deleteMyTrackedScholarship' : ActorMethod<[bigint], boolean>,
  'deleteSummerProgram' : ActorMethod<[bigint], boolean>,
  'deleteVolunteerEntry' : ActorMethod<[bigint], boolean>,
  'getAchievements' : ActorMethod<[], Array<AchievementEntry>>,
  'getAiSuggestions' : ActorMethod<[StudentProfile], AiSuggestion>,
  'getAlumniMessages' : ActorMethod<[bigint], Array<AlumniMessage>>,
  'getAnxietyRatings' : ActorMethod<[], Array<AnxietyRating>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCelebrationEvents' : ActorMethod<[], Array<CelebrationEvent>>,
  'getCollegeMatchScore' : ActorMethod<
    [bigint, string, StudentProfile],
    AiMatchScore
  >,
  'getColleges' : ActorMethod<[], Array<College>>,
  'getCollegesByCountry' : ActorMethod<[string], Array<College>>,
  'getCollegesByFinancialAid' : ActorMethod<[FinancialAidTier], Array<College>>,
  'getCourseRecommendations' : ActorMethod<
    [string, string],
    Array<CourseRecommendation>
  >,
  'getExtracurricularRecommendations' : ActorMethod<
    [StudentProfile],
    Array<ExtracurricularRecommendation>
  >,
  'getGeminiApiKeyStatus' : ActorMethod<[], boolean>,
  'getInternships' : ActorMethod<[], Array<InternshipEntry>>,
  'getInterviewQuestions' : ActorMethod<
    [string, string],
    Array<InterviewQuestion>
  >,
  'getLeadershipRoles' : ActorMethod<[], Array<LeadershipRole>>,
  'getMoodCheckIns' : ActorMethod<[], Array<MoodCheckIn>>,
  'getMyDeadlines' : ActorMethod<[], Array<CollegeDeadline>>,
  'getMyDocumentChecklist' : ActorMethod<[], Array<DocumentChecklistItem>>,
  'getMyOfficerProfile' : ActorMethod<[], [] | [AdmissionOfficer]>,
  'getMyScholarshipShortlist' : ActorMethod<[], Array<ScholarshipId>>,
  'getOfficerContent' : ActorMethod<[bigint], Array<OfficerContent>>,
  'getOfficerProfile' : ActorMethod<[], [] | [OfficerProfile]>,
  'getPortfolioChecklist' : ActorMethod<[], Array<PortfolioChecklistItem>>,
  'getSalaryBookmarks' : ActorMethod<[], Array<SalaryBookmark>>,
  'getSavedCareerPaths' : ActorMethod<[], Array<SavedCareerPath>>,
  'getScholarships' : ActorMethod<[], Array<Scholarship>>,
  'getStudentProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getSummerPrograms' : ActorMethod<[], Array<SummerProgram>>,
  'getVolunteerEntries' : ActorMethod<[], Array<VolunteerEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyApplications' : ActorMethod<[], Array<ApplicationEntry>>,
  'listMyEssayDrafts' : ActorMethod<[], Array<EssayDraft>>,
  'listMyStressCheckIns' : ActorMethod<[], Array<StressCheckIn>>,
  'listMyTasks' : ActorMethod<[], Array<TaskItem>>,
  'listMyTestScores' : ActorMethod<[], Array<TestScore>>,
  'listMyTrackedScholarships' : ActorMethod<[], Array<ScholarshipTracked>>,
  'listPendingOfficers' : ActorMethod<[], Array<OfficerProfile>>,
  'postAlumniMessage' : ActorMethod<[bigint, string], undefined>,
  'postOfficerContent' : ActorMethod<[OfficerContentInput], bigint>,
  'queryScholarships' : ActorMethod<[ScholarshipFilter], Array<Scholarship>>,
  'registerOfficer' : ActorMethod<[bigint, string], undefined>,
  'removeSalaryBookmark' : ActorMethod<[bigint], boolean>,
  'removeSavedCareerPath' : ActorMethod<[bigint], boolean>,
  'reviewEssay' : ActorMethod<[string, string], EssayReview>,
  'saveCareerPath' : ActorMethod<[string, string, string], SavedCareerPath>,
  'saveMyDeadlines' : ActorMethod<[Array<CollegeDeadline>], undefined>,
  'saveMyDocumentChecklist' : ActorMethod<
    [Array<DocumentChecklistItem>],
    undefined
  >,
  'saveMyScholarshipShortlist' : ActorMethod<[Array<ScholarshipId>], undefined>,
  'saveSalaryBookmark' : ActorMethod<
    [string, string, [] | [bigint], string],
    SalaryBookmark
  >,
  'saveStudentProfile' : ActorMethod<[StudentProfile], undefined>,
  'setGeminiApiKey' : ActorMethod<[string], undefined>,
  'submitInterviewAnswer' : ActorMethod<
    [string, string, string],
    InterviewFeedback
  >,
  'submitOfficerProfile' : ActorMethod<
    [string, string, string],
    OfficerProfile
  >,
  'toggleMyTask' : ActorMethod<[bigint], [] | [TaskItem]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMyApplication' : ActorMethod<
    [bigint, [] | [ApplicationStatus], [] | [string], [] | [string]],
    [] | [ApplicationEntry]
  >,
  'updateMyEssayDraft' : ActorMethod<
    [bigint, [] | [string], [] | [string], [] | [Array<string>]],
    [] | [EssayDraft]
  >,
  'updateMyTestScore' : ActorMethod<
    [bigint, [] | [Array<[string, bigint]>], [] | [string], [] | [bigint]],
    [] | [TestScore]
  >,
  'updateMyTrackedScholarship' : ActorMethod<
    [bigint, [] | [ScholarshipTrackedStatus], [] | [string], [] | [string]],
    [] | [ScholarshipTracked]
  >,
  'updateOfficerVerificationStatus' : ActorMethod<
    [UserId, OfficerVerificationStatus],
    boolean
  >,
  'upsertPortfolioChecklist' : ActorMethod<
    [Array<PortfolioChecklistItem>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];